version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306

  postgres:
    image: postgres:14.3-alpine
    restart: always
    platform: linux/x86_64
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080